config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to post_path(@post.id)
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :body, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= form_for(@post) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, id: :post_author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', posts_path %>


<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<dvi class="container">
  <div class="row">
    <div class="col-lg-4" style="background-color: orange;">
      <h2>サイドバー</h2>
    </div>
    <div class="col-lg-8">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Title</th>
            <th>Body</th>
            <th>Author</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @posts.each do |post| %>
            <tr>
              <td><%= post.title %></td>
              <td><%= post.body %></td>
              <td><%= post.author %></td>
              <td><%= link_to 'Show', post %></td>
              <td><%= link_to 'Edit', edit_post_path(post) %></td>
              <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</dvi>

<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-default" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for(@post) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, id: :post_author %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>